steps:
  - label: ":docker: Build image"
    key: image-build
    commands:
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9t5s3a7"
      - "docker build --progress=plain --file docker/Dockerfile.ci -t vllm-omni-ci ."
      - "docker tag vllm-omni-ci public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT"
      - "docker push public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT"
    agents:
      queue: "cpu_queue_premerge"

  # L2 Test
  - label: "Upload Ready Pipeline"
    depends_on: image-build
    key: upload-ready-pipeline
    if: build.branch != "main"
    commands:
      - buildkite-agent pipeline upload .buildkite/test-ready.yml
    agents:
      queue: "cpu_queue_premerge"

  # L3 Test
  - label: "Upload Merge Pipeline"
    depends_on: image-build
    key: upload-merge-pipeline
    if: build.branch == "main" && build.env("NIGHTLY") != "1"
    commands:
      - buildkite-agent pipeline upload .buildkite/test-merge.yml
    agents:
      queue: "cpu_queue_premerge"

  # L4 Test
  - label: "Upload Nightly Pipeline"
    depends_on: image-build
    key: upload-nightly-pipeline
    if: build.branch == "main" && build.env("NIGHTLY") == "1"
    commands:
      - buildkite-agent pipeline upload .buildkite/test-nightly.yml
    agents:
      queue: "cpu_queue_premerge"

  # Other Framework Test
  - label: ":docker: Build image for other framework"
    key: image-build-other-framework
    commands:
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9t5s3a7"
      - "docker build --progress=plain --file docker/Dockerfile.other -t vllm-omni-ci-other ."
      - "docker tag vllm-omni-ci-other public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:${BUILDKITE_COMMIT}-other-framework"
      - "docker push public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:${BUILDKITE_COMMIT}-other-framework"
    agents:
      queue: "cpu_queue_premerge"

  - label: "Test Other Framework"
    depends_on: image-build-other-framework
    key: test-other-framework
    if: build.branch != "main"
    commands:
      # sglang command
      - "sglang generate --model-path=Qwen/Qwen-Image --prompt='A fantasy landscape...' --width=1024 --height=1024 --num-inference-steps=10 --guidance-scale=4.0 --seed=42 --save-output --enable-torch-compile --warmup --dit-cpu-offload false --text-encoder-cpu-offload false --num-gpus=2 --ulysses-degree=2"
    agents:
      queue: "gpu_4_queue"
