steps:
  - label: "Omni Model Test with H100"
    timeout_in_minutes: 60
    depends_on: image-build
    if: build.env("NIGHTLY") == "1"
    commands:
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - pytest -s -v tests/e2e/online_serving/test_qwen3_omni_expansion.py
      - pytest -s -v tests/examples/online_serving/test_qwen3_omni.py
    agents:
      queue: "mithril-h100-pool"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT
                resources:
                  limits:
                    nvidia.com/gpu: 2
                volumeMounts:
                  - name: devshm
                    mountPath: /dev/shm
                  - name: hf-cache
                    mountPath: /root/.cache/huggingface
                env:
                  - name: HF_HOME
                    value: /root/.cache/huggingface
            nodeSelector:
              node.kubernetes.io/instance-type: gpu-h100-sxm
            volumes:
              - name: devshm
                emptyDir:
                  medium: Memory
              - name: hf-cache
                hostPath:
                  path: /mnt/hf-cache
                  type: DirectoryOrCreate

  - label: "Omni Model Test"
    timeout_in_minutes: 60
    depends_on: image-build
    if: build.env("NIGHTLY") == "1"
    if: build.env("NIGHTLY") == "1"
    commands:
      - export VLLM_LOGGING_LEVEL=DEBUG
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - pytest -s -v tests/examples/online_serving/test_qwen2_5_omni.py
      - export VLLM_LOGGING_LEVEL=DEBUG
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - pytest -s -v tests/examples/online_serving/test_qwen2_5_omni.py
    agents:
      queue: "gpu_4_queue" # g6.12xlarge instance on AWS, has 4 L4 GPU
    plugins:
      - docker#v5.2.0:
          image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT
          always-pull: true
          propagate-environment: true
          shm-size: "8gb"
          environment:
            - "HF_HOME=/fsx/hf_cache"
          volumes:
            - "/fsx/hf_cache:/fsx/hf_cache"

  - label: "Omni Model Perf Test"
    key: nightly-performance
    timeout_in_minutes: 120
    depends_on: image-build
    #TODO: Only for testing, will remove before merging to main
    # if: build.env("NIGHTLY") == "1"
    commands:
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - export BENCHMARK_DIR=tests
      - pytest -s -v tests/perf/scripts/run_benchmark.py
      - buildkite-agent artifact upload "tests/*.json"
    agents:
      queue: "mithril-h100-pool"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT
                resources:
                  limits:
                    nvidia.com/gpu: 2
                volumeMounts:
                  - name: devshm
                    mountPath: /dev/shm
                  - name: hf-cache
                    mountPath: /root/.cache/huggingface
                env:
                  - name: HF_HOME
                    value: /root/.cache/huggingface
            nodeSelector:
              node.kubernetes.io/instance-type: gpu-h100-sxm
            volumes:
              - name: devshm
                emptyDir:
                  medium: Memory
              - name: hf-cache
                hostPath:
                  path: /mnt/hf-cache
                  type: DirectoryOrCreate

  - label: "Nightly Perf Collection  & Email"
    key: nightly-perf-distribution
    depends_on: nightly-performance
    #TODO: Only for testing, will remove before merging to main
    # if: build.env("NIGHTLY") == "1"
    commands:
      - pip install openpyxl
      - export DEFAULT_INPUT_DIR=tests
      - export DEFAULT_OUTPUT_DIR=tests
      #TODO: Remove those secrets before merging to main
      - export SMTP_HOST=None
      - export SMTP_PORT=None
      - export SMTP_USERNAME=None
      - export SMTP_PASSWORD=None
      - export DAILY_EMAIL_LIST=None
      - buildkite-agent artifact download "tests/*.json" . --step nightly-performance
      - python tools/nightly/generate_nightly_perf_excel.py
      - python tools/nightly/send_nightly_perf_email.py --dry-run
      - buildkite-agent artifact upload "tests/*.xlsx"
    agents:
      queue: "cpu_queue_premerge"
