ARG SGLANG_BASE_IMAGE=lmsysorg/sglang
ARG SGLANG_BASE_TAG=latest
FROM ${SGLANG_BASE_IMAGE}:${SGLANG_BASE_TAG}

ARG APP_DIR=/workspace/vllm-omni
ARG CACHE_DIT_VERSION=1.3.0

WORKDIR ${APP_DIR}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y espeak-ng ffmpeg git sox libsox-fmt-all jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN  pip install --no-cache-dir "cache-dit==${CACHE_DIT_VERSION}"

RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
