ARG SGLANG_BASE_IMAGE=lmsysorg/sglang
ARG SGLANG_BASE_TAG=latest
FROM ${SGLANG_BASE_IMAGE}:${SGLANG_BASE_TAG}

ARG APP_DIR=/workspace/vllm-omni
WORKDIR ${APP_DIR}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y espeak-ng ffmpeg git sox libsox-fmt-all jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
